language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

script:
  - ./gradlew assemble
  - gem install bundler
  - bundle install
  - bundle exec danger --verbose # Verbose is useful for debugging when setting up
